/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Keep existing primary scale for backward compatibility
        primary: {
          DEFAULT: '#00236f',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        // Stitch Material Design 3 tokens
        'primary-container': '#1e3a8a',
        'on-primary': '#ffffff',
        'on-primary-container': '#90a8ff',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-fixed': '#00164e',
        'on-primary-fixed-variant': '#264191',
        'inverse-primary': '#b6c4ff',
        'secondary': '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary': '#4b1c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6e2c00',
        'on-tertiary-container': '#f39461',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#773205',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#faf8ff',
        'surface-dim': '#dad9e1',
        'surface-bright': '#faf8ff',
        'surface-variant': '#e3e1e9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3fa',
        'surface-container': '#eeedf4',
        'surface-container-high': '#e9e7ef',
        'surface-container-highest': '#e3e1e9',
        'on-surface': '#1a1b21',
        'on-surface-variant': '#444651',
        'surface-tint': '#4059aa',
        'inverse-surface': '#2f3036',
        'inverse-on-surface': '#f1f0f7',
        'outline': '#757682',
        'outline-variant': '#c5c5d3',
        'background': '#faf8ff',
        'on-background': '#1a1b21',
        // Keep backward-compat semantic aliases
        critical: '#dc2626',
        warning: '#f59e0b',
        success: '#16a34a',
        info: '#2563eb',
      },
      fontFamily: {
        'technical-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'technical-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      spacing: {
        'gutter': '16px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'unit': '4px',
      },
      animation: {
        'pulse-critical': 'pulse-ring-red 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        'subtle-pulse': 'subtle-pulse 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
      },
      keyframes: {
        'pulse-ring-red': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5', boxShadow: '0 0 0 0 rgba(186, 26, 26, 0.7)' },
          '70%': { transform: 'scale(1)', opacity: '1', boxShadow: '0 0 0 10px rgba(186, 26, 26, 0)' },
          '100%': { transform: 'scale(0.8)', opacity: '0.5', boxShadow: '0 0 0 0 rgba(186, 26, 26, 0)' },
        },
        'subtle-pulse': {
          '0%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0.4)' },
          '70%': { boxShadow: '0 0 0 6px rgba(186, 26, 26, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0)' },
        },
      },
    },
  },
  plugins: [],
};
